# Generated by fusen: do not edit by hand

#' Say good bye to someone
#' 
#' @param someone Character.
#' @return Side effect: A message in the console
#' @importFrom glue glue
#' @export
#' @examples

#' say_goodbye() #Good bye You !
#' say_goodbye(someone = "Christine") #Good bye Christine !
say_goodbye <- function(someone = "You") {
  message(glue("Good bye {someone} !"))
}
